services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - data:/data
    ports:
      - 7080:80

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - 3000:8080
    volumes:
      - open-webui:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    ports:
      - 3001:3001
    volumes:
      - uptime-kuma:/app/data

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 999:3000
    volumes:
      - ./homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HOMEPAGE_ALLOWED_HOSTS: gethomepage.dev *

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: always
    privileged: true
    network_mode: host

  # TODO use this
  # beszel-agent:
  #   image: henrygd/beszel-agent
  #   container_name: beszel-agent
  #   restart: unless-stopped
  #   network_mode: host
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     # monitor other disks / partitions by mounting a folder in /extra-filesystems
  #     # - /mnt/disk1/.beszel:/extra-filesystems/disk1:ro
  #   environment:
  #     LISTEN: 45876
  #     KEY: '<public key>'


volumes:
  data:
  open-webui: